#%RAML 1.0
title: Heritage Bookshop Sales Process API
description: Process API provides endpoints to accept sales transactions from different source (Orange App and Blue App) and Retrieve a sales transactoin by tsansaction id.
version: 1.0
mediaType: application/json
protocols:
  - HTTPS
uses:
  datatypes-library: library/datatypes-library.raml

/sales:
  post:
    description: Create a sales transaction
    displayName: Create a sales transaction
    body:
      application/json:
        type: datatypes-library.CreateSalesRequestSchema
        example: !include post_sales/examples/post_sales_app_request_examples.json
    responses:
      201:
        body:
          application/json:
            type: datatypes-library.CreateSalesResponseSchema
            example: !include post_sales/examples/post_sales_app_response_examples.json
      400:
        description: Error is a bad request on the payload, querystring, or headers.
        body:
          application/json:
      500:
        description: Something went wrong with the request.
        body:
          application/json:
  get:
    description: Retrieve sales by transaction id
    displayName: Retrieve sales by transaction id
    queryParameters:
      transactionId:
        type: string
        required: true
        description: "Unique identifier of the sales transaction to retrieve"
        example: "Orange-002"
    responses:
      200:
        body:
          application/json:
            type: datatypes-library.GetSalesResponseSchema
            example: !include get-sales/examples/get_sales_app_response_example.json
      400:
        description: Error is a bad request on the payload, querystring, or headers.
        body:
          application/json:
      500:
        description: Something went wrong with the request.
        body:
          application/json:
